import "../Day4.css";
export function ScheduleDay4() {
    return (
        <main>
            <div>
                <p>7:30</p>
                <p>朝食</p>
            </div>
            <div>
                <p>08:30</p>
                <div>
                    <p>バス</p>
                    <p>リーベルホテルアット</p>
                    <p>ユニバーサルスタジオジャパン</p>
                    <p>Liber Hotel At Universal Stadio Japan</p>
                </div>
            </div>
            ----------------
            <div>
                <p>1.嵐山ルート</p>
            </div>
            <div>
                <p>10:00</p>
                <div></div>
                <div>
                    <p>嵐山</p>
                    <p>Arashiyama</p>
                </div>
            </div>
            <div>
                <p>10:00</p>
                <div>
                    <p>観光</p>
                    <p>嵐山</p>
                    <img></img>
                </div>
            </div>
            <div>
                <p>昼食は各自</p>
            </div>
            <div>
                <p>13:50</p>
                <div>
                    <div>
                        <p>バス</p>
                        <div></div>
                    </div>
                    <div></div>
                    <div>
                        <p>嵐山</p>
                        <p>Arashiyama</p>
                    </div>
                </div>
            </div>
            --------------------------
            <div>
                <p>3.北野天満宮/錦市場ルート</p>
            </div>
            <div>
                <p>10:15</p>
                <div>
                    <div></div>
                    <div>
                        <p>北野天満宮</p>
                        <p>Kitano Tennmannguu</p>
                    </div>
                </div>
            </div>
            <div>
                <p>10:15</p>
                <div>
                    <p>観光</p>
                    <p>北野天満宮</p>
                    <img></img>
                </div>
            </div>
            <div>
                <p>昼食は自由</p>
            </div>
            <div>
                <p>14:10</p>
                <div>
                    <div>
                        <p>バス</p>
                        <div></div>
                    </div>
                    <div></div>
                    <div>
                        <p>清水駐車場</p>
                        <p>KiyomizuParking</p>
                    </div>
                </div>
            </div>
            --------------------------
        </main>
    );
}
